### ISSUE TITLE
Unexpected error WebGL2 not supported NULL

### ISSUE THREAD

**Issue by infowolfe** [aptakube/aptakube#18]
### Current and expected behavior

When clicking on "logs" I get an error.

When I click on "logs" within a pod, I should see the log output from the pod.

### Operating System

macOS Catalina 10.15.7 x86_64 universal build

### Environment

clientVersion:
  buildDate: "2022-08-23T17:44:59Z"
  compiler: gc
  gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2
  gitTreeState: clean
  gitVersion: v1.25.0
  goVersion: go1.19
  major: "1"
  minor: "25"
  platform: darwin/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-07-26T09:20:06Z"
  compiler: gc
  gitCommit: 2211759978749a9c2935fe2f8db1e6823c3c0bb1
  gitTreeState: clean
  gitVersion: v1.21.14-gke.2700
  goVersion: go1.16.15b7
  major: "1"
  minor: "21"
  platform: linux/amd64

**Comment by goenning** [comment]
hey @infowolfe , that's because we currently only support webgl2 log renderer on current version of Aptakube, which doesn't seem to be supported by your current Safari version. I think they added support in Safari 15.0, but only after 15.4 it became really stable.

On Aptakube 0.7.0 (due next week 🎉) we've added support for an alternative log rendered which should be supported on most systems, even on older Safari versions. 

I'll post an update here when it's released.

**Comment by infowolfe** [comment]
I'm on Safari Version 15.6.1 (15613.3.9.1.16, 15613)

**Comment by goenning** [comment]
Hmm, that's odd, could be something related to the combination of OS + Safari.

Want to try 0.7.0? There's a bunch of other log related improvements as well. It's not yet publicly released, but there's a .dmg here https://github.com/aptakube/aptakube/releases/tag/0.7.0

**Comment by goenning** [comment]
I'll close this for now, but please reopen if it's not resolved on Aptakube 0.7.1.
