### ISSUE TITLE
Reverse fonts on sidebar

### ISSUE THREAD

**Issue by mindovermiles262** [aptakube/aptakube#63]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

The font weights/sizes of the text sidebar of aptakube feel backwards to me. Headings are smaller in font and weight, while API Resources are larger and bolder. I would expect the opposite. In the attached screenshot I would change the font of the headings ("Cluster", "Workloads", etc) to be that of the items ("Secrets", "Config Maps", etc)

![image](https://user-images.githubusercontent.com/14863257/217336412-43f915f2-e8dc-450a-b9b5-d9ad71dc4990.png)

**Comment by goenning** [comment]
The design was inspired on macOS and Linear

<img width="1234" alt="Xnapper-2023-02-07-19 21 50" src="https://user-images.githubusercontent.com/94755/217344523-6c258674-6d1e-494b-8478-2247c462e51b.png">

![](https://linear.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fhero%404x.15e3a396.jpg&w=3840&q=75%201x)

And this is how it would look like if we inverted.

![image](https://user-images.githubusercontent.com/94755/217344790-6e854bf0-49ba-45d7-bfb2-7d6b3d077b0d.png)

Here's another version where they all have the same font size:

![image](https://user-images.githubusercontent.com/94755/217345496-a52c0533-0a0e-4f68-8ad2-32fc0f0c7841.png)

---

It actually doesn't look bad and it works quite well, maybe it's the fact that we have so many categories/resources? 

But I'm not really happy with the current nor theses ones I just posted, I think there's something missing on this navigation. It could be because we don't have icons, but it'd be way too much visual distraction to have icons for all items.

What you think about these two alternatives above? Does it look better than currently?

 I'll probably play with it a bit to see what other alternatives I can find and share the results here.

**Comment by mindovermiles262** [comment]
> And this is how it would look like if we inverted.

This one looks 💯 better. The white color of the headings clearly signal to me that it's a heading. The darker/less contrast (I don't know the correct term) color of the (gray) sub-items makes it easy to view and understand the hierarchy at a quick glance. With the different colors I don't feel icons are needed. 

I think the same-size font works fine too. The emphasis of the headings is expressed via the color. Smaller fonts also maximizes space for more resources.

+1 for the "inverted" screenshot with same size fonts.

**Comment by MattKetmo** [comment]
I quite disagree with the inverted choice.

Those "headings" here are secondary information. The resources name (Pod, Deployments, etc) are the main fields to look at.

Exactly like the macOS Finder example: you want your folders to appear bigger, not the fact that they are in "Favorite" our "iCloud".

Everyone knows the name of kube resources, but almost nobody knows in which category they should belong to. So no need to make those categories more important.

What could help is increasing slightly more the margin-top above those headings (like 2px more).

Icons might help too, in the sense of making resources in a separate vertical alignment from headings.

```
Heading 1
|_ Resource 1
|_ Resource 2

Heading 2
|_ Resource 1
|_ Resource 2
```

(Btw, what's the order criteria? Why not sorting resources alphabetically in each category?)

**Comment by goenning** [comment]
@mindovermiles262 @MattKetmo adding icons to all resources would be impossible, it's too many and too dynamic. 

However we could add them to the groups, what you think of this?


```
|_ Heading 1
Resource 1
Resource 2

|_ Heading 2
Resource 1
Resource 2
```

![image](https://github.com/aptakube/aptakube/assets/94755/80a25799-ac80-4c01-b807-cbc5ecbc11e8)

**Comment by MattKetmo** [comment]
hmm, not sure if icons make it better or worse ^^

(ps: who still clicks on the menu now that we have the command bar 😛)

**Comment by goenning** [comment]
Worse? 🙈 

A lot of people still use it though, so I'm trying to make it suck less.

**Comment by libracoder** [comment]
Its super confusing

**Comment by nusrath432** [comment]
Reversing fonts must be a priority - it is the most annoying thing with AptaKube - otherwise the light theme is much cleaner and better than K9s/Openlens (subjective opinion). Thanks

**Comment by goenning** [comment]
Is this looking better @libracoder @nusrath432 ?

1. Left border to highlight selectable resources
2. Chevron on categories (like Finder)
3. Higher contrast on current selected resource

<img width="765" alt="Screenshot 2024-06-11 at 20 10 19" src="https://github.com/aptakube/aptakube/assets/94755/c3f00c42-1347-49c2-9bde-f54a1ec6287e">

**Comment by timcole** [comment]
Everything having a blue border is so weird. :sob:
If you want the border can you at least make it grey or something.

**Comment by goenning** [comment]
Making it grey is the same as not having it at all
But I have to say though that after using it throughout the day I'm finding the blue border distracting.
I will just revert and keep it as similar as possible to macOS Finder.
