### ISSUE TITLE
Ability to refresh AKS token/identity

### ISSUE THREAD

**Issue by SWojtyla** [aptakube/aptakube#88]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

In Aptakube when your identity/login expired it loads forever while in (open)Lens it shows that you have to log in again.
It would be great to have a similar feature or at least show that there's something "wrong".
![image](https://user-images.githubusercontent.com/36441058/228492785-54841620-b335-49fa-9b84-bf5f262171b3.png)

**Comment by goenning** [comment]
Thanks for reporting this. This seems to be a problem with device code login only, I'll have a look.

In the meantime, have you considered using azure cli login flow instead of device code flow?

The dev experience using azure cli login is so much better, it automatically handles token expiration, it's more secure and you don't have to copy/paste that code. On top of that, it works fine perfectly with Aptakube :)

I wrote something about it a while ago in case you're interested https://aptakube.com/blog/how-to-use-azure-kubelogin

**Comment by SWojtyla** [comment]
Hey, thanks for the response !
I'll have a look into it. Thanks for the suggestion.

**Comment by SWojtyla** [comment]
Indeed it works perfectly with the cli flow!
 Might not be necessary/useful to fix this if it will be deprecated in a future version...

Will close this.
